name: bitbil
description: "Bitbil App"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
    
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  firebase_core: ^3.9.0
  cloud_firestore: 5.6.6
  camera: ^0.10.0

  flutter_dotenv: ^5.0.2
  google_generative_ai: ^0.4.1
  uuid: ^4.4.0
  flutter_chat_ui: ^1.6.12
  webview_flutter: ^4.7.0
  firebase_storage: ^12.4.5
  path_provider: ^2.0.11
  shared_preferences: ^2.5.3
  photo_manager: 3.6.4
  permission_handler: ^11.3.0
  intl: ^0.18.1


flutter_icons:
  android: true
  ios: true
  image_path: "assets/bitbil.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/bitbil.png

